import Head from "next/head";
import Layout from "../components/Layout";
import Home from "../components/Home";

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>RickNMorty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Home />
      </Layout>
    </div>
  );
}
